
/**************************************************************
 *	
 *	bgMusic, 8 bit, 11025Hz,
 *	1 channel, 405476 bytes/channel
 *	Total Size: 1 * 405476 + 4 (header) = 405520 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/wheelersutton/GoogleDrive/CS2261/FinalProject/FinalProject_DavidSutton/bgMusic.aiff
 *	Time-stamp: Tue Nov 29 14:49:15 2016
 *	
 **************************************************************/

#ifndef __BGMUSICH__
#define __BGMUSICH__

#define BGMUSICFREQ 11025
#define BGMUSICLEN 405476

extern const unsigned char bgMusic[405476];

#endif /* __BGMUSICH__ */
