
/**************************************************************
 *	
 *	bullet, 8 bit, 11025Hz,
 *	1 channel, 4525 bytes/channel
 *	Total Size: 1 * 4525 + 4 (header) = 4569 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/wheelersutton/GoogleDrive/CS2261/FinalProject/FinalProject_DavidSutton/bullet.aiff
 *	Time-stamp: Wed Nov 30 16:53:13 2016
 *	
 **************************************************************/

#ifndef __BULLETH__
#define __BULLETH__

#define BULLETFREQ 11025
#define BULLETLEN 4525

extern const unsigned char bullet[4525];

#endif /* __BULLETH__ */
