
/**************************************************************
 *	
 *	explosion, 8 bit, 11025Hz,
 *	1 channel, 23826 bytes/channel
 *	Total Size: 1 * 23826 + 4 (header) = 23870 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/wheelersutton/GoogleDrive/CS2261/FinalProject/FinalProject_DavidSutton/explosion.aiff
 *	Time-stamp: Fri Dec 09 00:53:53 2016
 *	
 **************************************************************/

#ifndef __EXPLOSIONH__
#define __EXPLOSIONH__

#define EXPLOSIONFREQ 11025
#define EXPLOSIONLEN 23826

extern const unsigned char explosion[23826];

#endif /* __EXPLOSIONH__ */
