
/**************************************************************
 *	
 *	maintheme, 8 bit, 11025Hz,
 *	1 channel, 625536 bytes/channel
 *	Total Size: 1 * 625536 + 4 (header) = 625580 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/wheelersutton/GoogleDrive/CS2261/FinalProject/FinalProject_DavidSutton/maintheme.aiff
 *	Time-stamp: Mon Dec 05 21:55:20 2016
 *	
 **************************************************************/

#ifndef __MAINTHEMEH__
#define __MAINTHEMEH__

#define MAINTHEMEFREQ 11025
#define MAINTHEMELEN 625536

extern const unsigned char maintheme[625536];

#endif /* __MAINTHEMEH__ */
