
/**************************************************************
 *	
 *	menubutton, 8 bit, 11025Hz,
 *	1 channel, 8821 bytes/channel
 *	Total Size: 1 * 8821 + 4 (header) = 8865 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/wheelersutton/GoogleDrive/CS2261/FinalProject/FinalProject_DavidSutton/menubutton.aiff
 *	Time-stamp: Mon Dec 05 22:18:13 2016
 *	
 **************************************************************/

#ifndef __MENUBUTTONH__
#define __MENUBUTTONH__

#define MENUBUTTONFREQ 11025
#define MENUBUTTONLEN 8821

extern const unsigned char menubutton[8821];

#endif /* __MENUBUTTONH__ */
