
/**************************************************************
 *	
 *	nameselectsound, 8 bit, 11025Hz,
 *	1 channel, 353 bytes/channel
 *	Total Size: 1 * 353 + 4 (header) = 397 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/wheelersutton/GoogleDrive/CS2261/FinalProject/FinalProject_DavidSutton/nameselectsound.aiff
 *	Time-stamp: Sat Dec 10 00:03:28 2016
 *	
 **************************************************************/

#ifndef __NAMESELECTSOUNDH__
#define __NAMESELECTSOUNDH__

#define NAMESELECTSOUNDFREQ 11025
#define NAMESELECTSOUNDLEN 353

extern const unsigned char nameselectsound[353];

#endif /* __NAMESELECTSOUNDH__ */
