
/**************************************************************
 *	
 *	pausesound, 8 bit, 11025Hz,
 *	1 channel, 6544 bytes/channel
 *	Total Size: 1 * 6544 + 4 (header) = 6588 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/wheelersutton/GoogleDrive/CS2261/FinalProject/FinalProject_DavidSutton/pausesound.aiff
 *	Time-stamp: Mon Dec 05 21:55:57 2016
 *	
 **************************************************************/

#ifndef __PAUSESOUNDH__
#define __PAUSESOUNDH__

#define PAUSESOUNDFREQ 11025
#define PAUSESOUNDLEN 6544

extern const unsigned char pausesound[6544];

#endif /* __PAUSESOUNDH__ */
